
class Human
{
    private int age;
    private String name;

    // constructor 
    // constructor does not have a return type; it is a special type of method
    // used for initialising default values to instance variables
    // Always called as soon as any object is created
    // the name of constructor shld be same as class name

   public  Human() // default constructor
   {
    age=12;
    name="jack";
   }

   public  Human(int a,String n) // parameterized constructor because it takes parameters
   {
    age=a;
    name=n;
   }

   // constructors generated by IDE

    public Human(String name) //  parameterized constructor with only name as parameter
    {
    this.name = name; 
    }

    public Human(int age)  //  parameterized constructor with only age as parameter
     {
        name="hugo"; // initialised name manually
        this.age = age;
     }



    //setters and getters 

    public void setage(int a) // setter
    {
        age=a;
    }

    public void setname(String n) // setter
    {
        name=n;
    }

    public int getage() // getter
    {
        return age;
    }

    public String getname() // getter
    {
        return name;
    } 
}

public class fullconstructor
{
    public static void main(String args [] )
    {
        Human h1= new Human();
        System.out.println(h1.getname()); // default value of string
        System.out.println(h1.getage()); // default value of int

        h1.setage(30);
        h1.setname("priyanshu");
        System.out.println(h1.getname() + " : " + h1.getage());

        Human h2= new Human(18 ,"kate");
        System.out.println(h2.getname() + " : " + h2.getage());

        Human h3= new Human("sawyer");
        System.out.println(h3.getname() + " : " + h3.getage());

        Human h4= new Human(50);
        System.out.println(h4.getname() + " : " + h4.getage());
    } 
}

/* output

jack
12
priyanshu : 30
kate : 18
sawyer : 0
hugo : 50

*/




 

