package tools;

public  class Human
{
    private int age;
    private String name;

    // constructor 
    // constructor does not have a return type; it is a special type of method
    // used for initialising default values to instance variables
    // Always called as soon as any object is created
    // the name of constructor shld be same as class name

   public  Human() // default constructor
   {
    age=12;
    name="jack";
   }

   public  Human(int a,String n) // parameterized constructor because it takes parameters
   {
    age=a;
    name=n;
   }

   // constructors generated by IDE

    public Human(String name) //  parameterized constructor with only name as parameter
    {
    this.name = name; 
    }

    public Human(int age)  //  parameterized constructor with only age as parameter
     {
        name="hugo"; // initialised name manually
        this.age = age;
     }

     // setters and getters
    
    public void setage(int a) // setter
    {
        age=a;
    }

    public void setname(String n) // setter
    {
        name=n;
    }

    public int getage() // getter
    {
        return age;
    }

    public String getname() // getter
    {
        return name;
    }

    // using  "this" keyword in setters
    
    public int getAge() // getter
    {
        return age;
    }

    public String getName() // getter
    {
        return name;
    }
    
    //since we are using same variable name (age here) in setting the values.. the interpreter gets confused which age we are referring to (the instance age or local age)

    // this keyword signifies that the variable after "this" points to the current object (the object which is calling the method)

    public void setAge(int age) // setter
    {
        this.age = age;
    }
    
    //since we are using same variable name (name here) in setting the values.. the interpreter gets confused which age we are referring to (the instance age or local age)

    // this keyword signifies that the variable after "this" points to the current object (the object which is calling the method)

    public void setName(String name) // setter
    {
        this.name = name;
    }  
}


    

